# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agua',
            fields=[
                ('id_agua', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField(verbose_name='valor')),
                ('unidad', models.CharField(default='l', max_length=32)),
                ('estado', models.NullBooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id_tem', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('hora', models.TimeField()),
                ('agua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Arduinitos.Agua')),
            ],
        ),
        migrations.CreateModel(
            name='Luz',
            fields=[
                ('id_luz', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField(verbose_name='valor')),
                ('unidad', models.CharField(default='lm', max_length=32)),
                ('estado', models.NullBooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id_temp', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField(verbose_name='valor')),
                ('unidad', models.CharField(default='\xb0C', max_length=32)),
                ('estado', models.NullBooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='informacion',
            name='luz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Arduinitos.Luz'),
        ),
        migrations.AddField(
            model_name='informacion',
            name='temperatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Arduinitos.Temperatura'),
        ),
    ]
